# Generated by Django 5.1.1 on 2025-09-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vr_conv_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
    ]
